"""Inventory upstream HLE registrations before duplicating an Xbox handler.

Registration means a callable is wired into the core linker; it does not prove
that its semantics are complete or that the source compiles for UWP.
"""

import json
import re
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
XBOX = ROOT / "xbox"
CATALOG = ROOT / "src/core/aerolib/aerolib.inl"
SOURCE = ROOT / "src/core/libraries"
OUTPUT = XBOX / "artifacts/core-hle-inventory.json"
HEADER = XBOX / "Generated Files/CoreHleInventory.h"


def write_header(rows: list[dict], path: Path) -> None:
    entries = "\n".join(
        "    {" + json.dumps(row["nid"]) + ", " +
        json.dumps(";".join(row["registered_in"])) + "}," for row in rows)
    source = """// Generated by audit_core_hle.py. Registration is not completeness proof.
#pragma once
#include <algorithm>
#include <iterator>
#include <string_view>
namespace Lab::CoreHleInventory {
struct Registration { std::string_view nid; std::string_view sources; };
inline constexpr Registration Entries[] = {
""" + entries + """
};
inline Registration const* Find(std::string_view nid) noexcept {
    const auto found = std::lower_bound(std::begin(Entries), std::end(Entries), nid,
        [](Registration const& row, std::string_view key) { return row.nid < key; });
    return found != std::end(Entries) && found->nid == nid ? found : nullptr;
}
} // namespace Lab::CoreHleInventory
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(source, encoding="utf-8")


def main() -> None:
    names = dict(re.findall(r'STUB\("([^"]+)",\s*([^\s)]+)\)',
                            CATALOG.read_text(encoding="utf-8")))
    registrations: dict[str, list[str]] = defaultdict(list)
    for path in sorted(SOURCE.rglob("*.cpp")):
        source = path.read_text(encoding="utf-8")
        for nid in set(re.findall(r'LIB_FUNCTION\s*\(\s*"([^"]+)"', source)):
            registrations[nid].append(path.relative_to(ROOT).as_posix())

    xbox_source = (XBOX / "HleDispatcher.cpp").read_text(encoding="utf-8")
    resolve = xbox_source.split("HleResolution HleDispatcher::Resolve(", 1)[1]
    resolve = resolve.split("const auto slot =", 1)[0]
    xbox_names = set(re.findall(r'name\s*==\s*"([^"]+)"', resolve))

    rows = [
        {
            "nid": nid,
            "name": names.get(nid, ""),
            "registered_in": paths,
            "xbox_handler_name_match": names.get(nid, "") in xbox_names,
        }
        for nid, paths in sorted(registrations.items())
    ]
    output = {
        "description": "Core HLE registrations are reuse candidates, not UWP compatibility proof.",
        "summary": {
            "core_registered_nids": len(rows),
            "xbox_name_matches": sum(row["xbox_handler_name_match"] for row in rows),
            "xbox_name_scan_limit": "Direct name == comparisons in HleDispatcher::Resolve only",
        },
        "registrations": rows,
    }
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(output, ensure_ascii=False, indent=2) + "\n",
                      encoding="utf-8")
    write_header(rows, HEADER)
    print(f"Core HLE inventory: {len(rows)} registrations; "
          f"{output['summary']['xbox_name_matches']} Xbox name matches")


if __name__ == "__main__":
    main()
